# Generated by Django 4.1.6 on 2023-02-03 13:13

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('buyers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('cars_to_sell', models.ManyToManyField(blank=True, related_name='cars_to_sell', to='car.car')),
                ('preferable_cars', models.ManyToManyField(blank=True, related_name='preferable_cars', to='car.car')),
                ('sold_cars', models.ManyToManyField(blank=True, related_name='sold_for_customer_cars', to='car.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesForCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_start', models.DateField()),
                ('discount_size', models.DecimalField(blank=True, decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_end', models.DateField()),
                ('cars_on_sales', models.ManyToManyField(limit_choices_to={'sold_to_customer': False, 'sold_to_showroom': True}, to='car.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
