# Generated by Django 4.1.5 on 2023-02-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_price'),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='cars_to_sell',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='preferable_cars',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='sold_cars',
        ),
        migrations.AddField(
            model_name='showroom',
            name='cars_to_sell',
            field=models.ManyToManyField(related_name='cars_to_sell', to='car.car'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='preferable_cars',
            field=models.ManyToManyField(related_name='preferable_cars', to='car.car'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='sold_cars',
            field=models.ManyToManyField(related_name='sold_for_customer_cars', to='car.car'),
        ),
    ]
