# Generated by Django 4.1.6 on 2023-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_initial'),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='available_cars',
            field=models.ManyToManyField(blank=True, related_name='available_cars', to='car.availablecar'),
        ),
    ]
