# Generated by Django 4.1.6 on 2023-02-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='available_cars',
        ),
        migrations.AddField(
            model_name='availablecar',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_cars', to='showroom.showroom'),
        ),
    ]
