# Generated by Django 4.1.6 on 2023-02-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_sold_to_customer_car_sold_to_showroom'),
        ('showroom', '0002_salesforcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforcustomer',
            name='cars_on_sales',
            field=models.ManyToManyField(limit_choices_to={'sold_to_showroom:True', 'sold_to_customer:False'}, to='car.car'),
        ),
    ]
