# Generated by Django 4.1.6 on 2023-02-09 11:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_remove_producer_available_cars_and_more'),
        ('customer', '0001_initial'),
        ('showroom', '0002_remove_showroom_available_cars_availablecar_showroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='buyer',
        ),
        migrations.AddField(
            model_name='availablecar',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_cars_for_producer', to='producer.producer'),
        ),
        migrations.AddField(
            model_name='history',
            name='buyer_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_customer', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='history',
            name='buyer_showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_showroom', to='showroom.showroom'),
        ),
        migrations.AddField(
            model_name='history',
            name='count',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='whole_price',
            field=models.DecimalField(decimal_places=0, default=120000, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availablecar',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_cars_for_showroom', to='showroom.showroom'),
        ),
    ]
