# Generated by Django 4.1.6 on 2023-02-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_delete_carsell'),
        ('showroom', '0003_remove_history_buyer_availablecar_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
