# Generated by Django 4.1.6 on 2023-02-03 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_sold_to_customer_car_sold_to_showroom'),
        ('showroom', '0003_salesforcustomer_cars_on_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforcustomer',
            name='discount_size',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforcustomer',
            name='cars_on_sales',
            field=models.ManyToManyField(limit_choices_to={'sold_to_customer': False, 'sold_to_showroom': True}, to='car.car'),
        ),
    ]
