# Generated by Django 4.1.6 on 2023-02-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('car', '0003_car_sold_to_customer_car_sold_to_showroom'),
        ('showroom', '0004_salesforcustomer_discount_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='buyers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='cars_to_sell',
            field=models.ManyToManyField(blank=True, related_name='cars_to_sell', to='car.car'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='preferable_cars',
            field=models.ManyToManyField(blank=True, related_name='preferable_cars', to='car.car'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='sold_cars',
            field=models.ManyToManyField(blank=True, related_name='sold_for_customer_cars', to='car.car'),
        ),
    ]
