# Generated by Django 4.1.6 on 2023-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_preferablecar_availablecar'),
        ('showroom', '0004_alter_discount_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferablecar',
            name='preferable_car',
        ),
        migrations.AlterField(
            model_name='showroom',
            name='preferable_cars',
            field=models.ManyToManyField(blank=True, related_name='preferable_cars', to='car.preferablecar'),
        ),
        migrations.DeleteModel(
            name='AvailableCar',
        ),
        migrations.DeleteModel(
            name='PreferableCar',
        ),
    ]
