# Generated by Django 4.1.6 on 2023-02-27 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_alter_discount_date_of_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
