# Generated by Django 4.1.6 on 2023-02-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('year_of_establishment', models.DateTimeField()),
                ('available_cars', models.ManyToManyField(related_name='available_cars', to='car.car')),
                ('buyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('sold_cars', models.ManyToManyField(related_name='sold_cars', to='car.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
