# Generated by Django 4.1.6 on 2023-02-13 09:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_buyer', to='showroom.showroom')),
                ('sold_car', models.ManyToManyField(related_name='sold_car_for_showroom', to='car.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('year_of_establishment', models.DateTimeField()),
                ('discount', models.ManyToManyField(blank=True, related_name='discount_for_showroom', to='showroom.discount')),
                ('history', models.ManyToManyField(blank=True, related_name='history_of_producer', to='producer.history')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
