# Generated by Django 4.1.5 on 2023-02-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_price'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='available_cars',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='sold_cars',
        ),
        migrations.AddField(
            model_name='producer',
            name='available_cars',
            field=models.ManyToManyField(related_name='available_cars', to='car.car'),
        ),
        migrations.AddField(
            model_name='producer',
            name='sold_cars',
            field=models.ManyToManyField(related_name='sold_cars', to='car.car'),
        ),
    ]
