# Generated by Django 4.1.6 on 2023-02-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_alter_showroom_buyers_alter_showroom_cars_to_sell_and_more'),
        ('car', '0003_car_sold_to_customer_car_sold_to_showroom'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='buyers',
        ),
        migrations.AlterField(
            model_name='producer',
            name='sold_cars',
            field=models.ManyToManyField(blank=True, related_name='sold_cars', to='car.car'),
        ),
        migrations.AddField(
            model_name='producer',
            name='buyers',
            field=models.ManyToManyField(blank=True, to='showroom.showroom'),
        ),
    ]
