# Generated by Django 4.1.6 on 2023-02-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='balance',
        ),
    ]
