# Generated by Django 4.1.6 on 2023-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_remove_producer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='available_cars',
        ),
        migrations.AlterField(
            model_name='producer',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history_of_producer', to='producer.history'),
        ),
    ]
