repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: migrations/
      - id: end-of-file-fixer
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
#  - repo: https://github.com/psf/black
#    rev: 23.1.0
#    hooks:
#      - id: black
#        exclude: migrations/
