repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
              ^
          )
      - id: end-of-file-fixer
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        exclude: |
          (?x)(
              ^frontend/
          )
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: |
          (?x)(
              ^frontend/
          )
