version: "3.9"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis
    restart: always
    volumes:
      - ./:/code/
  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./:/code/
    command: [ 'celery','-A','api','worker' ]
    env_file:
      - .env
  celery-beats:
    restart: always
    build:
      context: .
    volumes:
      - ./:/code/
    command: [ 'celery', '-A' ,'api' ,'beat', '-l' ,'INFO', '--scheduler','django_celery_beat.schedulers:DatabaseScheduler' ]
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - "5555:5555"
    depends_on:
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "10080:80"
      - "10443:443"
    depends_on:
      - app
      - flower

volumes:
  static:
    driver: local
  pg_data:
    driver: local
