version: "3.9"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - db
  redis:
    image: redis
    restart: always
  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./customer:/app/src/customer
    command: [ 'celery','-A','api','worker' ]
    env_file:
      - .env.dev
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.dev