version: "3.9"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis
    restart: always
    volumes:
      - ./:/code/
  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./:/code/
    command: [ 'celery','-A','api','worker' ]
    env_file:
      - .env
  celery-beats:
    restart: always
    build:
      context: .
    volumes:
      - ./:/code/
    command: [ 'celery', '-A' ,'api' ,'beat', '-l' ,'INFO', '--scheduler','django_celery_beat.schedulers:DatabaseScheduler' ]
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
#    static_volume:
#      driver: local
  pg_data:
    driver: local