# Generated by Django 4.1.5 on 2023-02-01 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_price'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='purchased_cars',
        ),
        migrations.AddField(
            model_name='customer',
            name='purchased_cars',
            field=models.ManyToManyField(to='car.car'),
        ),
    ]
