# Generated by Django 4.1.6 on 2023-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_initial'),
        ('customer', '0002_alter_user_balance_alter_user_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchased_cars',
            field=models.ManyToManyField(blank=True, to='car.car'),
        ),
    ]
