# Generated by Django 4.1.5 on 2023-01-26 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('audi', 'Audi'), ('bmw3', 'Bmw'), ('mercedes A', 'Mercedes'), ('lexus RX', 'Lexus')], max_length=15)),
                ('color', models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=15)),
                ('power', models.CharField(choices=[('120', 'Power1'), ('200', 'Power2'), ('350', 'Power3'), ('420', 'Power4')], max_length=15)),
                ('price', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(15000)])),
            ],
        ),
    ]
