# Generated by Django 4.1.6 on 2023-02-02 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('power', models.CharField(blank=True, choices=[('120', 'Horses120'), ('200', 'Horses200'), ('350', 'Horses350'), ('420', 'Horses420')], max_length=15)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
