# Generated by Django 4.1.5 on 2023-01-26 12:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, choices=[('audi', 'Audi'), ('bmw', 'Bmw'), ('mercedes', 'Mercedes'), ('lexus', 'Lexus')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, choices=[('120', 'Power1'), ('200', 'Power2'), ('350', 'Power3'), ('420', 'Power4')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.SmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
