# Generated by Django 4.1.6 on 2023-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='ModelName',
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
