# Generated by Django 4.1.6 on 2023-02-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_model_modelname_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='sold_to_showroom',
            field=models.BooleanField(default=False),
        ),
    ]
