# Generated by Django 4.1.6 on 2023-02-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carsell_remove_car_price_remove_car_sold_to_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarSell',
        ),
    ]
