# Generated by Django 4.1.6 on 2023-02-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showroom", "0003_remove_showroom_available_cars"),
        ("car", "0003_alter_availablecar_producer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="availablecar",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="showroom.discount",
            ),
        ),
    ]
