# Generated by Django 4.1.6 on 2023-02-27 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0004_availablecar_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="name",
        ),
    ]
