name: Test App
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repos code
        uses: actions/checkout@v3
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev --system --deploy
      - name: docker up
        run: docker-compose up
      - name: Testing app
        run: pytest .
      - name: docker down
        run: docker-compose down
