name: Test App
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repos code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pipenv install --dev --system --deploy
      - name: Test application
        run: pytest .
