name: Test App
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repos code
        uses: actions/checkout@v3
      - name: Install pipenv
        run: pip install pipenv
      - name: Run docker-compose
        uses: isbang/compose-action@v1.4.1
        with:
          down-flags: "--volumes"
          up-flags: "--build"
          services: |
            app
            db
